# compilando os executáveis
grafos: src/graph.c src/graph.h src/main.c
	gcc -Wall -Wextra -std=c99 src/graph.c src/main.c -o grafos

.PHONY: run clean

# executando o programa
run: grafos
	./grafos


